name: GameLauncherUpdater Build

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'      
    - name: Build with MSBuild
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'    
      run: msbuild  GameLauncherUpdater.sln -p:Configuration=Release
    - name: Upload Artifacts
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' 
      uses: actions/upload-artifact@v2
      with:
        name: ArtifactBuild
        path: |
          ${{ github.workspace }}/GameLauncherUpdater/bin/Release/GameLauncherUpdater.exe