name: GameLauncherUpdater Build

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'      
    - name: Build with MSBuild
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'    
      run: msbuild  GameLauncherUpdater.sln -p:Configuration=Release
    - name: Upload Artifacts
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' 
      uses: actions/upload-artifact@v2
      with:
        name: ArtifactBuild
        path: |
          ${{ github.workspace }}/GameLauncherUpdater/bin/Release/GameLauncherUpdater.exe